### ISSUE TITLE
Move "Firebase Settings" section above "Logs Settings" section

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/reddit-tag#3]
I was checking the different sGTM tags Stape has developed and I see some tags that do not follow the standard way of structuring and naming sections.

Is it possible to move the "Firebase Settings" section above the "Logs Settings" section?

This is how it is implemented in the [Google](https://github.com/stape-io/gads-offline-conversion-tag) & [Microsoft](https://github.com/stape-io/microsoft-ads-offline-conversion-tag) tags.

**Comment by Bukashk0zzz** [comment]
Thanks. We will do this. 

cc @kHorozhanov

**Comment by kHorozhanov** [comment]
Hi @alexgarciab,
Thanks for reporting this issue.
We will fix it by removing this section, as it isn't needed now during the updated authorization flow.

**Comment by Bukashk0zzz** [comment]
done

**Comment by alexgarciab** [comment]
@kHorozhanov great! using the Conversion Access Token is way more convenient than the oAuth credentials flow.
